package com.botmaker.shared.github;

/**
 * Static configuration for the federated bot-sharing gallery.
 *
 * <p>Two values are maintainer-owned and must be filled in before publishing / the gallery work
 * end-to-end (see the project plan):
 * <ul>
 *   <li>{@link #OAUTH_CLIENT_ID} — register a GitHub OAuth App with device flow enabled and paste its
 *       (public) client id here. While blank, publishing degrades gracefully ("publishing not configured").</li>
 *   <li>{@link #INDEX_OWNER}/{@link #INDEX_REPO} — the curated index repo holding {@code index.json}. While
 *       it doesn't exist, Studio's {@code GitHubGallery.browse()} simply returns an empty catalog.</li>
 * </ul>
 * Browsing / installing public bots needs no GitHub account; only publishing does.
 *
 * <p><b>It lives in {@code botmaker-shared} since 2026-09-05</b>, with the rest of
 * {@code com.botmaker.shared.github}, because Studio is no longer the only operator of these repositories:
 * {@code botmaker-dashboard} reads the same registry, the same gallery and the same pull requests. A second
 * copy of the owner/repo names is a second thing to edit when one of them moves — and the device flow beside
 * it is emphatically not code that may exist twice. Nothing here names a Studio type; the javadoc below
 * mentions Studio's readers as prose rather than as links, on purpose.
 */
public final class GitHubConfig {

    private GitHubConfig() {}

    public static final String OAUTH_CLIENT_ID = "Ov23lizugeHUiWl7WZhQ";

    public static final String INDEX_OWNER = "LiQiyeDev";
    public static final String INDEX_REPO = "botmaker-gallery";

    /** The Studio's own repo, whose GitHub Releases host the app installers (used by the in-app updater). */
    public static final String STUDIO_OWNER = "LiQiyeDev";
    public static final String STUDIO_REPO = "BotMaker-Studio";

    /**
     * The {@code botmaker} command-line tool's repo, whose latest release tag is the version Studio's
     * {@code CliUpdateService} compares the installed CLI against.
     *
     * <p>A repo name rather than a Maven coordinate on purpose: Studio does not depend on {@code botmaker-cli}
     * and must not — they are two hosts of one platform, and what they share lives in {@code botmaker-studio-api}
     * and {@code botmaker-plugin-host}. Reading the tag here is what lets a Studio that has not been
     * re-released still offer a newer CLI.
     */
    public static final String CLI_OWNER = "LiQiyeDev";
    public static final String CLI_REPO = "botmaker-cli";

    /** Umbrella repo that receives in-app bug reports (Help ▸ Report Issue…). */
    public static final String ISSUE_OWNER = "LiQiyeDev";
    public static final String ISSUE_REPO = "botmaker";
    public static final String INDEX_BRANCH = "main";

    /**
     * The generated catalog, read by Studio's {@code GitHubGallery.browse()}.
     *
     * <p><b>Read only.</b> Studio used to publish by rewriting this whole array, which made every concurrent
     * submission a merge conflict and every delisting a whole-file diff. The gallery's own CI generates it
     * from {@link #ENTRIES_DIR} now, and refuses a pull request that edits it. The path is a compatibility
     * promise in the other direction — a Studio already in the wild has this URL compiled into it — so it
     * must not move.
     */
    public static final String INDEX_PATH = "index.json";

    /**
     * The generated catalog with every listing and its tier, read by Studio since 2026-09-16.
     *
     * <p>{@link #INDEX_PATH} could not grow a tier: every Studio in the wild reads it as a bare array and would
     * list a Community bot exactly like a Vetted one. So that file now holds only Vetted bots in its old
     * shape, and this one is the whole gallery as {@code {"schemaVersion": 2, "bots": [...]}}. Like the index
     * it is generated by the gallery's CI and never written by a client.
     */
    public static final String CATALOG_PATH = "catalog.json";

    /** Where one bot's entry lives, and what Studio's {@code BotPublisher} writes: {@code bots/<owner>-<repo>.json}. */
    public static final String ENTRIES_DIR = "bots";

    /**
     * Maintainer-only records saying which release of a bot is vetted: {@code vetted/<owner>-<repo>.json}.
     *
     * <p>A directory of its own rather than a field in the entry, because the entry is its author's to rewrite
     * on every publish and a field would be something every submission can set.
     */
    public static final String VETTED_DIR = "vetted";

    /**
     * The plugin index — the gallery's sibling, read by Studio's {@code PluginRegistry}.
     *
     * <p>Studio only ever <em>reads</em> it: a plugin is submitted with {@code botmaker publish} from the
     * CLI, whose validator is the same code the registry's CI runs. There is deliberately no publish path
     * here, because the checks that decide a submission need the plugin's build, not a bot's editor.
     */
    public static final String REGISTRY_OWNER = "LiQiyeDev";
    public static final String REGISTRY_REPO = "botmaker-plugin-registry";

    /** Discovery topic also applied to published repos (secondary signal; the index repo is authoritative). */
    public static final String TOPIC = "botmaker-bot";

    public static final String API_BASE = "https://api.github.com";
    public static final String DEVICE_CODE_URL = "https://github.com/login/device/code";
    public static final String ACCESS_TOKEN_URL = "https://github.com/login/oauth/access_token";
    /**
     * Full {@code repo} rather than {@code public_repo}: the VCS panel's Push button creates and pushes to a
     * <em>private</em> backup repo, which {@code public_repo} cannot do. Tokens issued before this change keep
     * their narrower scope, so the private-repo calls translate the resulting 403/404 into a "sign out and back
     * in" hint rather than a raw API error.
     */
    public static final String SCOPE = "repo";

    /**
     * The path of one bot's entry file, {@code bots/<owner>-<repo>.json}.
     *
     * <p>The filename is the bot's identity, which is what makes two submissions two files that cannot
     * conflict — and makes a delisting a deletion rather than a rewrite.
     */
    public static String entryPath(String owner, String repo) {
        return ENTRIES_DIR + "/" + owner + "-" + repo + ".json";
    }

    /** The path of one bot's vetting record, {@code vetted/<owner>-<repo>.json} — named like its entry. */
    public static String vettedPath(String owner, String repo) {
        return VETTED_DIR + "/" + owner + "-" + repo + ".json";
    }

    /**
     * The organization the gallery and the registry move to, read <b>before</b> their current owner
     * (2026-09-18).
     *
     * <p>A raw URL is compiled into every shipped Studio, and GitHub Pages does not redirect after a transfer,
     * so the move is done in two steps: first a Studio that reads the new owner and falls back to the old one
     * ships and is adopted, and only then do the two repositories move. Until then the new owner answers 404
     * and costs one request per browse. After the move, {@link #INDEX_OWNER} and {@link #REGISTRY_OWNER}
     * become this, and the fallback keeps reading the old one for as long as GitHub redirects it.
     */
    public static final String NEXT_OWNER = "BotMakerDev";

    /** Raw (CDN) URLs of the legacy index, in the order to try: Vetted bots only, in the array shape older Studios read. */
    public static java.util.List<String> indexRawUrls() {
        return rawUrls(INDEX_REPO, INDEX_PATH, INDEX_OWNER);
    }

    /** Raw (CDN) URLs of the tiered catalog, in the order to try — no API rate limit, no auth. */
    public static java.util.List<String> catalogRawUrls() {
        return rawUrls(INDEX_REPO, CATALOG_PATH, INDEX_OWNER);
    }

    /** Raw (CDN) URLs of the plugin index, in the order to try — generated by the registry's CI, never written here. */
    public static java.util.List<String> registryIndexRawUrls() {
        return rawUrls(REGISTRY_REPO, INDEX_PATH, REGISTRY_OWNER);
    }

    /** {@link #NEXT_OWNER}'s copy first, then {@code owner}'s; one URL when they are the same owner. */
    private static java.util.List<String> rawUrls(String repo, String path, String owner) {
        return java.util.stream.Stream.of(NEXT_OWNER, owner)
                .distinct()
                .map(o -> "https://raw.githubusercontent.com/" + o + "/" + repo + "/" + INDEX_BRANCH + "/" + path)
                .toList();
    }

    /**
     * Release-archive endpoint for a tag. Deliberately the API's {@code zipball} rather than a direct
     * {@code codeload.github.com} URL: the API form honours an {@code Authorization} header (so a private or
     * rate-limited repo still installs) and answers a 302 to a signed codeload URL that needs no auth of its
     * own — the client follows it.
     */
    public static String archiveUrl(String owner, String repo, String tag) {
        return API_BASE + "/repos/" + owner + "/" + repo + "/zipball/refs/tags/" + tag;
    }

    /** REST endpoint for creating an issue on the umbrella repo (used with an authenticated token). */
    public static String issuesApiUrl() {
        return API_BASE + "/repos/" + ISSUE_OWNER + "/" + ISSUE_REPO + "/issues";
    }

    /** Browser URL of the umbrella repo's "New Issue" page (no auth handled by the app; the browser session is). */
    public static String newIssueBrowserUrl() {
        return "https://github.com/" + ISSUE_OWNER + "/" + ISSUE_REPO + "/issues/new";
    }

    public static boolean isPublishingConfigured() {
        return !OAUTH_CLIENT_ID.isBlank();
    }

    public static boolean isGalleryConfigured() {
        return !INDEX_OWNER.isBlank() && !INDEX_REPO.isBlank();
    }

    public static boolean isRegistryConfigured() {
        return !REGISTRY_OWNER.isBlank() && !REGISTRY_REPO.isBlank();
    }
}
